/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LocationInput = IDL.Record({
  'floor' : IDL.Text,
  'name' : IDL.Text,
  'building' : IDL.Text,
  'description' : IDL.Text,
  'roomNumber' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'lab' : IDL.Null,
  'other' : IDL.Null,
  'office' : IDL.Null,
  'department' : IDL.Null,
  'classroom' : IDL.Null,
});
export const Location = IDL.Record({
  'id' : IDL.Text,
  'floor' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'building' : IDL.Text,
  'description' : IDL.Text,
  'roomNumber' : IDL.Text,
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLocation' : IDL.Func([LocationInput], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLocation' : IDL.Func([IDL.Text], [], []),
  'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchLocations' : IDL.Func([IDL.Text], [IDL.Vec(Location)], ['query']),
  'updateLocation' : IDL.Func([IDL.Text, LocationInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LocationInput = IDL.Record({
    'floor' : IDL.Text,
    'name' : IDL.Text,
    'building' : IDL.Text,
    'description' : IDL.Text,
    'roomNumber' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'lab' : IDL.Null,
    'other' : IDL.Null,
    'office' : IDL.Null,
    'department' : IDL.Null,
    'classroom' : IDL.Null,
  });
  const Location = IDL.Record({
    'id' : IDL.Text,
    'floor' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'building' : IDL.Text,
    'description' : IDL.Text,
    'roomNumber' : IDL.Text,
    'category' : Category,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLocation' : IDL.Func([LocationInput], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLocation' : IDL.Func([IDL.Text], [], []),
    'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchLocations' : IDL.Func([IDL.Text], [IDL.Vec(Location)], ['query']),
    'updateLocation' : IDL.Func([IDL.Text, LocationInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };